from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = (
    AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
)
prompt = """
请将下面的一段文本翻译成中文:
Sichuan Attracts over 6 Million Visits during the New Year Holiday, with Increased Visits and Ticket Revenue\nIn Sichuan Province during the New Year holiday, 661 A-level scenic spots included in the statistical scope received 6.2386 million visits and generated 53.4773 million yuan in ticket revenue.\nCompared with the same period in 2021 with 637 key scenic spots being included in the statistical scope, there is an increase of 8.84% and 3.84%, respectively.\nWinter tourism was popular.\nOver the holiday, ice and snow tourism, spring tourism, and sunshine and health tourism were in great demand.\nMany scenic areas such as Mount Emei, Xiling Snow Mountain, Wawu Mountain, Bipenggou Valley, and Mount Siguniang were filled to capacity for two days in a row.\nAba Tibetan and Qiang Autonomous Prefecture, Ganzi Tibetan Autonomous Prefecture, Liangshan Yi Autonomous Prefecture, and Panzhihua City saw a remarkable rise in the number of winter tourists. According to some data, 131 A-level scenic areas in these places had received 467,800 visits and generated 3.0080 million yuan, up 9.52% and 17.64% compared with the same period of 2021, respectively.\nSanxingdui Museum, Jiuzhai Valley, and Chengdu Research Base of Giant Panda Breeding remained popular.\nOver the holiday, 15 scenic areas having 5A-level ratings in the province received 315,000 visits, up 12.13% year on year, and generated 11.7609 million yuan in ticket revenue.\nAmong others, Sanxingdui Museum, Jiuzhai Valley, and Chengdu Research Base of Giant Panda Breeding received 17,977, 4,106, and 35,346 visits and generated 808,900 yuan, 289,400 yuan, and 1,391,500 yuan in ticket revenue, respectively.\nTourism featuring short-distance visits or visits to surrounding suburbs were in majority.\nOver the holiday, short-distance visits to surrounding famous ancient cities and towns and scenic areas with family or friends by car were most popular.\nScenic areas such as hometown of Deng Xiaoping and Floraland Amusement Park attracted a vast number of tourists.\nRural tourism was a main choice.\nParent-child experience, rural hiking, picking experience, enjoying rustic food and buying local special products were very popular among tourists.\nSansheng Flower Town in Chengdu received 223,000 visits and Luodai Ancient Town received 112,400 visits.\nCulture and tourism activities were diverse.\nMany places in the province launched diverse culture and tourism activities around food, accommodation, transportation, tour, shopping, and entertainment such as concerts to celebrate the New Year, artistic performances, visits to parks, and delicious food, making people's spiritual and cultural life richer.
"""
response, history = model.chat(tokenizer, prompt, history=[])
print(response)
